const Images = [{image: require('./images/cusin_1.jpg')}];

export const data = [
  {
    title: 'Vegetable_items',
    data: [
      {
        id: 1,
        title: 'panner tikka massala',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 270,
      },
      {
        id: 2,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 270,
      },
      {
        id: 3,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 230,
      },
      {
        id: 4,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 240,
      },
      {
        id: 5,
        title: 'jera aloo',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 200,
      },
      {
        id: 6,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 270,
      },
    ],
  },
  {
    title: 'chicken_items',
    data: [
      {
        id: 7,
        title: 'panner tikka massala',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 270,
      },
      {
        id: 8,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 270,
      },
      {
        id: 9,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 230,
      },
      {
        id: 10,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 240,
      },
      {
        id: 11,
        title: 'jera aloo',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 200,
      },
      {
        id: 12,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 270,
      },
    ],
  },
  {
    title: 'Fast_foods',
    data: [
      {
        id: 13,
        title: 'panner tikka massala',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 270,
      },
      {
        id: 14,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 270,
      },
      {
        id: 15,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 230,
      },
      {
        id: 16,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 240,
      },
      {
        id: 17,
        title: 'jera aloo',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 200,
      },
      {
        id: 18,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 270,
      },
    ],
  },
  {
    title: 'Breads_item',
    data: [
      {
        id: 19,
        title: 'panner tikka massala',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 270,
      },
      {
        id: 20,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 270,
      },
      {
        id: 21,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 230,
      },
      {
        id: 22,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 240,
      },
      {
        id: 23,
        title: 'jera aloo',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 200,
      },
      {
        id: 24,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 270,
      },
    ],
  },
  {
    title: 'Vegetable_items',
    data: [
      {
        id: 25,
        title: 'panner tikka massala',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 270,
      },
      {
        id: 26,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 270,
      },
      {
        id: 27,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 230,
      },
      {
        id: 28,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 240,
      },
      {
        id: 29,
        title: 'jera aloo',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 200,
      },
      {
        id: 30,
        title: 'malai kofta',
        description: 'good in taste must try',
        image: Images[0].image,
        rating: 90,
        review: 99,
        price: 270,
      },
    ],
  },
];
